name: Daily Weather Report

on:
  # Run on a schedule (every day at 8 AM UTC)
  schedule:
    - cron: '0 8 * * *'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:
    inputs:
      locations:
        description: 'Locations: zip codes or city names (semicolon-separated)'
        required: false
        default: ''
        type: string

jobs:
  send-weather-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run weather bot
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # Use input locations if provided, otherwise use default list
        # Examples: "10001,US" (NYC zip), "London,UK", "Springfield,IL,US"
        LOCATIONS: ${{ github.event.inputs.locations || '84117,US;84121,US;84101,US;84108,US' }}
      run: |
        python weather_bot.py
    
    - name: Log completion
      run: |
        echo "✅ Weather report sent successfully at $(date)"